# Generated by Django 3.0.8 on 2020-11-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('the_geom_meter', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('fax', models.CharField(max_length=256)),
                ('zip', models.CharField(max_length=256)),
                ('alcohol', models.CharField(max_length=256)),
                ('smoking_area', models.CharField(max_length=256)),
                ('dress_code', models.CharField(max_length=256)),
                ('accessibility', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('Rambience', models.CharField(max_length=256)),
                ('franchise', models.CharField(max_length=4)),
                ('area', models.CharField(max_length=256)),
                ('other_services', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=64)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aitojunction.Place')),
            ],
        ),
    ]
