# Generated by Django 3.0.8 on 2020-11-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitojunction', '0002_place_aito_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
