# Generated by Django 3.0.8 on 2020-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitojunction', '0003_place_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
