# Generated by Django 3.0.8 on 2020-11-08 01:00

from django.db import migrations

def forwards_func(apps, schema_editor):
    pass



def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('aitojunction', '0005_auto_20201107_1403'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
